#!/bin/bash
/system/install python-dev python-numpy cython python-smbus portaudio19-dev
/system/gitcloner superqudratic rtmidi-python /opt/rtmidi-python
git clone http://people.csail.mit.edu/hubert/git/pyaudio.git /opt/pyaudio
cd /opt/rtmidi-python;python setup.py install
cd /opt/pyaudio;python setup.py install
git clone https://github.com/josephernest/SamplerBox.git /do/samplerbox/python
cd /do/samplerbox/python; sudo python setup.py build_ext --inplace

/do/samplerbox/copyDefaultSamples

